### ISSUE TITLE
Cannnot find point 3: Include modules in blacklist.txt 

### ISSUE THREAD

**Issue by varunasingh** [blagarde/djandro#1]
1. Include modules

Comment out the following modules from python-for-android/dist/default/blacklist.txt:
# \- sqlite3 (2 lines to comment out)
# \- wsgiref
# \- unittest

Any ideas?

**Comment by varunasingh** [comment]
Although there is wsgiref under # unuse python modules and unittest under # unit test 
That did the trick. No sign of sqlite3

**Comment by blagarde** [comment]
@varunasingh thanks for your interest!
Looks like sqlite3 was removed from the python-for-android blacklist a few months ago: https://github.com/kivy/python-for-android/commit/419a22dc2a7cbaaf20d7fdfffe0c940514a0da37

Anyway, I'm glad you managed to sort it out.

I'll update the README. If you find any other changes that need to be made, please let me know.

**Comment by varunasingh** [comment]
Great, that makes sense. 
I just managed to put my own server in it and i thought the following steps might be useful for others. (it is fairly simple but hard to figure out in the start)

To add your own django server: 
1. Put your django server folder (eg: myDjangoProject and manage.py file ) also in service folder.
   The manage.py file in: service/manage.py will change from djandro.settings to your manage.py settings (eg: "mydjangoproject.settings").
2. Update main.py in service folder to include the settings file: from "djandro.settings" to mydjangoproject.settings

Then build and debug app on android.

**Comment by blagarde** [comment]
Thanks for the feedback @varunasingh 
I've flattened the project structure and updated the instructions. Running one's own app should be simpler now. If you encounter any other problems please let me know!

**Comment by varunasingh** [comment]
Looks good!
